// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: container/v1/container.proto

package containerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerRequest) Reset() {
	*x = GetContainerRequest{}
	mi := &file_container_v1_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerRequest) ProtoMessage() {}

func (x *GetContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerRequest.ProtoReflect.Descriptor instead.
func (*GetContainerRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{0}
}

func (x *GetContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,4,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_container_v1_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{1}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *Container) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerResponse) Reset() {
	*x = GetContainerResponse{}
	mi := &file_container_v1_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerResponse) ProtoMessage() {}

func (x *GetContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerResponse.ProtoReflect.Descriptor instead.
func (*GetContainerResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{2}
}

func (x *GetContainerResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type CreateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_container_v1_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{3}
}

func (x *CreateContainerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_container_v1_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContainerResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_container_v1_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{5}
}

func (x *ListContainersRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListContainersRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *ListContainersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListContainersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListContainersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_container_v1_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{6}
}

func (x *ListContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type CreateContainerBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerBatchRequest) Reset() {
	*x = CreateContainerBatchRequest{}
	mi := &file_container_v1_container_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerBatchRequest) ProtoMessage() {}

func (x *CreateContainerBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerBatchRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{7}
}

func (x *CreateContainerBatchRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateContainerBatchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateContainerBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerBatchResponse) Reset() {
	*x = CreateContainerBatchResponse{}
	mi := &file_container_v1_container_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerBatchResponse) ProtoMessage() {}

func (x *CreateContainerBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerBatchResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{8}
}

func (x *CreateContainerBatchResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type AssignWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWarehouseRequest) Reset() {
	*x = AssignWarehouseRequest{}
	mi := &file_container_v1_container_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWarehouseRequest) ProtoMessage() {}

func (x *AssignWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWarehouseRequest.ProtoReflect.Descriptor instead.
func (*AssignWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{9}
}

func (x *AssignWarehouseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignWarehouseRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

type AssignWarehouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWarehouseResponse) Reset() {
	*x = AssignWarehouseResponse{}
	mi := &file_container_v1_container_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWarehouseResponse) ProtoMessage() {}

func (x *AssignWarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWarehouseResponse.ProtoReflect.Descriptor instead.
func (*AssignWarehouseResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{10}
}

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   string                 `protobuf:"bytes,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_container_v1_container_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{11}
}

func (x *Warehouse) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWarehousesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesRequest) Reset() {
	*x = ListWarehousesRequest{}
	mi := &file_container_v1_container_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesRequest) ProtoMessage() {}

func (x *ListWarehousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesRequest.ProtoReflect.Descriptor instead.
func (*ListWarehousesRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{12}
}

type ListWarehousesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesResponse) Reset() {
	*x = ListWarehousesResponse{}
	mi := &file_container_v1_container_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesResponse) ProtoMessage() {}

func (x *ListWarehousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesResponse.ProtoReflect.Descriptor instead.
func (*ListWarehousesResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{13}
}

func (x *ListWarehousesResponse) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

type ContainerType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerType) Reset() {
	*x = ContainerType{}
	mi := &file_container_v1_container_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerType) ProtoMessage() {}

func (x *ContainerType) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerType.ProtoReflect.Descriptor instead.
func (*ContainerType) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{14}
}

func (x *ContainerType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ContainerType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListContainerTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainerTypesRequest) Reset() {
	*x = ListContainerTypesRequest{}
	mi := &file_container_v1_container_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainerTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainerTypesRequest) ProtoMessage() {}

func (x *ListContainerTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainerTypesRequest.ProtoReflect.Descriptor instead.
func (*ListContainerTypesRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{15}
}

type ListContainerTypesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerTypes []*ContainerType       `protobuf:"bytes,1,rep,name=container_types,json=containerTypes,proto3" json:"container_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListContainerTypesResponse) Reset() {
	*x = ListContainerTypesResponse{}
	mi := &file_container_v1_container_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainerTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainerTypesResponse) ProtoMessage() {}

func (x *ListContainerTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainerTypesResponse.ProtoReflect.Descriptor instead.
func (*ListContainerTypesResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{16}
}

func (x *ListContainerTypesResponse) GetContainerTypes() []*ContainerType {
	if x != nil {
		return x.ContainerTypes
	}
	return nil
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_container_v1_container_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_container_v1_container_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_v1_container_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_container_v1_container_proto_rawDescGZIP(), []int{18}
}

var File_container_v1_container_proto protoreflect.FileDescriptor

const file_container_v1_container_proto_rawDesc = "" +
	"\n" +
	"\x1ccontainer/v1/container.proto\x12\fcontainer.v1\"%\n" +
	"\x13GetContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x89\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fwarehouse_id\x18\x04 \x01(\tR\vwarehouseId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"M\n" +
	"\x14GetContainerResponse\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.container.v1.ContainerR\tcontainer\",\n" +
	"\x16CreateContainerRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"P\n" +
	"\x17CreateContainerResponse\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.container.v1.ContainerR\tcontainer\"\x94\x01\n" +
	"\x15ListContainersRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"Q\n" +
	"\x16ListContainersResponse\x127\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x17.container.v1.ContainerR\n" +
	"containers\"G\n" +
	"\x1bCreateContainerBatchRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"W\n" +
	"\x1cCreateContainerBatchResponse\x127\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x17.container.v1.ContainerR\n" +
	"containers\"K\n" +
	"\x16AssignWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\"\x19\n" +
	"\x17AssignWarehouseResponse\"B\n" +
	"\tWarehouse\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\tR\vwarehouseId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x17\n" +
	"\x15ListWarehousesRequest\"Q\n" +
	"\x16ListWarehousesResponse\x127\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x17.container.v1.WarehouseR\n" +
	"warehouses\"7\n" +
	"\rContainerType\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1b\n" +
	"\x19ListContainerTypesRequest\"b\n" +
	"\x1aListContainerTypesResponse\x12D\n" +
	"\x0fcontainer_types\x18\x01 \x03(\v2\x1b.container.v1.ContainerTypeR\x0econtainerTypes\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x16\n" +
	"\x14UpdateStatusResponse2\x92\x06\n" +
	"\x10ContainerService\x12U\n" +
	"\fGetContainer\x12!.container.v1.GetContainerRequest\x1a\".container.v1.GetContainerResponse\x12^\n" +
	"\x0fCreateContainer\x12$.container.v1.CreateContainerRequest\x1a%.container.v1.CreateContainerResponse\x12[\n" +
	"\x0eListContainers\x12#.container.v1.ListContainersRequest\x1a$.container.v1.ListContainersResponse\x12m\n" +
	"\x14CreateContainerBatch\x12).container.v1.CreateContainerBatchRequest\x1a*.container.v1.CreateContainerBatchResponse\x12^\n" +
	"\x0fAssignWarehouse\x12$.container.v1.AssignWarehouseRequest\x1a%.container.v1.AssignWarehouseResponse\x12[\n" +
	"\x0eListWarehouses\x12#.container.v1.ListWarehousesRequest\x1a$.container.v1.ListWarehousesResponse\x12g\n" +
	"\x12ListContainerTypes\x12'.container.v1.ListContainerTypesRequest\x1a(.container.v1.ListContainerTypesResponse\x12U\n" +
	"\fUpdateStatus\x12!.container.v1.UpdateStatusRequest\x1a\".container.v1.UpdateStatusResponseBUZSgithub.com/ljubushkin/container-management-service/pkg/api/container/v1;containerv1b\x06proto3"

var (
	file_container_v1_container_proto_rawDescOnce sync.Once
	file_container_v1_container_proto_rawDescData []byte
)

func file_container_v1_container_proto_rawDescGZIP() []byte {
	file_container_v1_container_proto_rawDescOnce.Do(func() {
		file_container_v1_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_container_v1_container_proto_rawDesc), len(file_container_v1_container_proto_rawDesc)))
	})
	return file_container_v1_container_proto_rawDescData
}

var file_container_v1_container_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_container_v1_container_proto_goTypes = []any{
	(*GetContainerRequest)(nil),          // 0: container.v1.GetContainerRequest
	(*Container)(nil),                    // 1: container.v1.Container
	(*GetContainerResponse)(nil),         // 2: container.v1.GetContainerResponse
	(*CreateContainerRequest)(nil),       // 3: container.v1.CreateContainerRequest
	(*CreateContainerResponse)(nil),      // 4: container.v1.CreateContainerResponse
	(*ListContainersRequest)(nil),        // 5: container.v1.ListContainersRequest
	(*ListContainersResponse)(nil),       // 6: container.v1.ListContainersResponse
	(*CreateContainerBatchRequest)(nil),  // 7: container.v1.CreateContainerBatchRequest
	(*CreateContainerBatchResponse)(nil), // 8: container.v1.CreateContainerBatchResponse
	(*AssignWarehouseRequest)(nil),       // 9: container.v1.AssignWarehouseRequest
	(*AssignWarehouseResponse)(nil),      // 10: container.v1.AssignWarehouseResponse
	(*Warehouse)(nil),                    // 11: container.v1.Warehouse
	(*ListWarehousesRequest)(nil),        // 12: container.v1.ListWarehousesRequest
	(*ListWarehousesResponse)(nil),       // 13: container.v1.ListWarehousesResponse
	(*ContainerType)(nil),                // 14: container.v1.ContainerType
	(*ListContainerTypesRequest)(nil),    // 15: container.v1.ListContainerTypesRequest
	(*ListContainerTypesResponse)(nil),   // 16: container.v1.ListContainerTypesResponse
	(*UpdateStatusRequest)(nil),          // 17: container.v1.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),         // 18: container.v1.UpdateStatusResponse
}
var file_container_v1_container_proto_depIdxs = []int32{
	1,  // 0: container.v1.GetContainerResponse.container:type_name -> container.v1.Container
	1,  // 1: container.v1.CreateContainerResponse.container:type_name -> container.v1.Container
	1,  // 2: container.v1.ListContainersResponse.containers:type_name -> container.v1.Container
	1,  // 3: container.v1.CreateContainerBatchResponse.containers:type_name -> container.v1.Container
	11, // 4: container.v1.ListWarehousesResponse.warehouses:type_name -> container.v1.Warehouse
	14, // 5: container.v1.ListContainerTypesResponse.container_types:type_name -> container.v1.ContainerType
	0,  // 6: container.v1.ContainerService.GetContainer:input_type -> container.v1.GetContainerRequest
	3,  // 7: container.v1.ContainerService.CreateContainer:input_type -> container.v1.CreateContainerRequest
	5,  // 8: container.v1.ContainerService.ListContainers:input_type -> container.v1.ListContainersRequest
	7,  // 9: container.v1.ContainerService.CreateContainerBatch:input_type -> container.v1.CreateContainerBatchRequest
	9,  // 10: container.v1.ContainerService.AssignWarehouse:input_type -> container.v1.AssignWarehouseRequest
	12, // 11: container.v1.ContainerService.ListWarehouses:input_type -> container.v1.ListWarehousesRequest
	15, // 12: container.v1.ContainerService.ListContainerTypes:input_type -> container.v1.ListContainerTypesRequest
	17, // 13: container.v1.ContainerService.UpdateStatus:input_type -> container.v1.UpdateStatusRequest
	2,  // 14: container.v1.ContainerService.GetContainer:output_type -> container.v1.GetContainerResponse
	4,  // 15: container.v1.ContainerService.CreateContainer:output_type -> container.v1.CreateContainerResponse
	6,  // 16: container.v1.ContainerService.ListContainers:output_type -> container.v1.ListContainersResponse
	8,  // 17: container.v1.ContainerService.CreateContainerBatch:output_type -> container.v1.CreateContainerBatchResponse
	10, // 18: container.v1.ContainerService.AssignWarehouse:output_type -> container.v1.AssignWarehouseResponse
	13, // 19: container.v1.ContainerService.ListWarehouses:output_type -> container.v1.ListWarehousesResponse
	16, // 20: container.v1.ContainerService.ListContainerTypes:output_type -> container.v1.ListContainerTypesResponse
	18, // 21: container.v1.ContainerService.UpdateStatus:output_type -> container.v1.UpdateStatusResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_container_v1_container_proto_init() }
func file_container_v1_container_proto_init() {
	if File_container_v1_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_container_v1_container_proto_rawDesc), len(file_container_v1_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_container_v1_container_proto_goTypes,
		DependencyIndexes: file_container_v1_container_proto_depIdxs,
		MessageInfos:      file_container_v1_container_proto_msgTypes,
	}.Build()
	File_container_v1_container_proto = out.File
	file_container_v1_container_proto_goTypes = nil
	file_container_v1_container_proto_depIdxs = nil
}
